#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

leftwm-command "UnloadTheme"

killall picom
killall polybar
killall dunst
killall flameshot
killall pamac
killall pasystray
killall protonvpn-app
killall xautolock
killall xss-lock
killall parcellite

kill $(ps aux | grep "layout.sh" | grep -v grep | awk '{print $2}')
