#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down

run () {
    if [ -x $(command -v "$1") ]; then
        if ! pgrep $1; then
            $@&
        fi
    fi
}

#boot compton or picom if it exists
if ! pgrep -x "picom" > /dev/null
then
    nohup picom --config "$SCRIPTPATH"/picom/picom.conf > /dev/null 2>&1 &
else
    pkill picom
    nohup picom --config "$SCRIPTPATH"/picom/picom.conf > /dev/null 2>&1 &
fi

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
run feh --bg-scale --randomize "$SCRIPTPATH/images/wallpapers"

#start the autolocker
run "$SCRIPTPATH"/scripts/autolock-script

# Start xss-lock to lock on system suspend
run "$SCRIPTPATH"/scripts/xsslock-script

# PA Sys Tray
run pasystray &

# extra utils to make this theme a little more homey
run dunst -config ~/.config/dunst/dunstrc &

# Something is causing the mouse to map lefthanded, possibly something in kde, though plasma works fine //shrug
# run xmodmap -e "pointer = 1 2 3"
run "$SCRIPTPATH"/scripts/xmodmap-script

# launch protonvpn if available
run protonvpn-cli c -f # safe to call over and over

# We want the kde/gnome polkit auth agent running for mounting hd and stuff
# run /usr/libexec/kf5/polkit-kde-authentication-agent-1 &
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# launch file manager if available
# run dolphin --daemon & 
run pcmanfm -d &
# run thunar --daemon &

# launch network-manager applet, but only if it's not already running
# This is needed for vpn
run nm-applet --indicator &

# launch synergy if available
# run synergy &

# Clipboard manager
run clipit &

# Screenshot tool
run flameshot &

#boot  polybar
index=0
id=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$id"
  monitor="${monitors[index]}" workspace="$id" width="$(( width - 16 ))" offsetx="$(( 8 + x ))" polybar -c "$SCRIPTPATH"/polybar/config.ini "$barname" &> /dev/null &
  let id=id+1
done
